### ISSUE TITLE
WebDriverScreenshotOnFailure takes screenshot twice for example scenario.

### ISSUE THREAD

**Issue by juperala** [jbehave/jbehave-web#20]
Taking screenshot of failure using [WebDriverScreenshotOnFailure.java](https://github.com/jbehave/jbehave-web/blob/master/web-selenium/src/main/java/org/jbehave/web/selenium/WebDriverScreenshotOnFailure.java) causes duplicate (overridden) screenshot taken for the last example in the scenario. If the scenario has teardown behavior, such as user logout, after each example scenario, this causes faulty screenshot taken for the last example in the scenario.

```
Scenario: Failing scenario
Given User <id> is logged in
When user completes transaction
Then transaction is completed

Examples:
|id|
|A|
|B|
|C|
```

In the above scenario, if the user is logged out in the *@AfterScenario(uponType = ScenarioType.EXAMPLE)* annotation, the screenshot of failure is shown correctly for examples A and B, but for the example C the screenshot is taken twice and last one overrides the correct one.

The first screenshot is taken by *WebDriverScreenshotOnFailure.afterScenarioWithExamplesFailure()* and the overriding screenshot is taken by *WebDriverScreenshotOnFailure.afterScenarioFailure()*. As the user is logged out between these two, you will see a screenshot showing page after the user was logged out instead of the actual failure page.

**Comment by paul-hammant** [comment]
Can you make a self-container Github repo that contains the `pom.xml` and `src/main/test/*` bits and pieces needed for for us to reproduce?

**Comment by juperala** [comment]
Sure,  I'll try to create clean project with reproducible error.

Just one question. For now I am using Jbehave only on legacy test suite that still relies on Selenium 2 and the stable version of jbehave-web-selenium (version 3.x.x something). That has critical limitations on the browser versions that are supported.

I Tried to create clean Maven project with Selenium 3, jbehave-core:4.3.1, and jbehave-web-selenium 4.0-beta-1. When running it with jbehave-maven-plugin:4.3.1 run into bunch of dedendency errors that I need to somehow resolve. Are there any working Maven example project or template for using latest jbehave-web-selenium with Selenium 3 and jbehave-maven-plugin?

**Comment by paul-hammant** [comment]
We're only going to solve this for "latest"

Your root cause isn't "screen shot problems" perhaps it is "unable to run JBehaveWeb with latest 3.1.x Selenium - right ???

**Comment by juperala** [comment]
Afaik there hasn't been any relevant changes to the WebDriverScreenshotOnFailure.java class, so the issue should still be present with the latest jbehave-web-selenium. Just need to get it working correctly to reproduce the issue. I'll get back on it.

But would appreciate if someone could link example of working pom.xml configuration for jbehave-web-selenium 4.0-beta-1.

**Comment by juperala** [comment]
I finally got the latest preview version (jbehave-web-selenium:4.0-beta-1) to work with Selenium 3. The problem I had was trying to use the deprecated/deleted guava method MoreExecutors.sameThreadExecutor() as described in the documentation http://jbehave.org/reference/web/preview/using-selenium.html.

However, I wasn't able to reproduce the original issue that we are experiencing with our test suite that is still using the stable version and Selenium 2. I'll close this issue and reopen it if the issue becomes reproducible with the latest preview versions.

**Comment by paul-hammant** [comment]
Is there a pull-request coming for us to apply to JBehave-web, maybe?  For the benefit of all users?
